const router = require('express').Router();

const fetch = require("node-fetch");
const bodyParser = require('body-parser');
const express = require('express');
let app = express();
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

const authCheck = (req, res, next) => {
    if(!req.user){
        res.redirect('/auth/login');
    } else{
        next(); //go onto next middleware
    }
};

router.get('/', authCheck, (req, res) => {
   res.render('profile', { user: req.user });
});

function getDate(){
    const today = new Date();
    const date = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();
    const time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
    return date+' '+time;
}

//http://localhost:3000/profile/generatePlaylist?genre=<GENRE>&duration=<DURATION>
router.get('/generatePlaylist', function(req, res) {
    let genre = req.query.title;
    let duration = req.query.duration;
    let counter = 0;
    let l1 = 'Location'; //req.query.start;
    let l2 = 'Destination'; //req.query.end;

    let tracks = {};
    let redirectURL = '';
    let playlistID = '';

    //create playlist
    let body = {
        'name': 'TYR Playlist - ' + l1 + ' to ' + l2 + '(' + getDate() + ')',
        'description': 'Playlist for ride from ' + l1 + ' to ' + l2 + '. Generated by Tune Your Ride.',
        'public': false
    };

    let endpoint = 'https://api.spotify.com/v1/users/'+req.user.spotifyId+'/playlists';
    fetch(endpoint, {
        method: 'post',
        body:    JSON.stringify(body),
        headers: { 'Authorization': 'Bearer ' + req.user.accessToken },
    })
        .then(response => {
            return response.json();
        })
        .then(data => {
            //console.log(data);
            playlistID = data.id;
            redirectURL = data.external_urls.spotify;
        })
        .then(findTracks) //find tracks to put into tracks variable
        .then(addTracks) //add tracks into playlist
        .then(redirectToSpotify)
        .catch(err => {
            console.log('Invalid Api Endpoint!');
            res.render('index', { title: 'The Error Page' });
        });

    function findTracks(){
        tracks = {};

        //while counter < duration, add tracks
        console.log('tracks found!')
    }

    function addTracks() {
        fetch('https://api.spotify.com/v1/playlists/'+ playlistID + '/tracks', {
            method: 'post',
            body:    JSON.stringify(tracks),
            headers: { 'Authorization': 'Bearer ' + req.user.accessToken },});
        console.log('tracks added to playlist!');
    }

    function redirectToSpotify(){
        console.log('redirecting to spotify - ' + redirectURL);
        res.redirect(redirectURL);
    }
});


module.exports = router;